type: object
title: Ocean CD Workload Migration SpotDeployment Spec
description: >
  Contains Workload's Migration SpotDeployment Spec.
properties:
  minReadySeconds:
    type: int
  paused:
    type: boolean
  progressDeadlineSeconds:
    type: int
  revisionHistoryLimit:
    type: int
  selector:
    type: object
    properties:
      matchExpressions:
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            operator:
              type: string
            values:
              type: array
              items:
                type: string
            additionalProperties:
              type: object
              additionalProperties:
                type: object
      matchLabels:
        type: object
        additionalProperties:
          type: string
      additionalProperties:
        type: object
        additionalProperties:
          type: object
  replicas:
    type: int
  template:
    type: object
    properties:
      metadata:
        type: object
        $ref: "../schemas/oceanCDWorkloadsMigrationMetaData.yaml"
      spec:
        type: object
        properties:
          activeDeadlineSeconds:
            type: long
          affinity:
            type: object
          automountServiceAccountToken:
            type: boolean
          containers:
            type: array
            items:
              type: object
          dnsConfig:
            type: object
          dnsPolicy:
            type: string
          enableServiceLinks:
            type: boolean
          ephemeralContainers:
            type: array
            items:
              type: object
          hostAliases:
            type: array
            items:
              type: object
          hostIPC:
            type: boolean
          hostNetwork:
            type: boolean
          hostPID:
            type: boolean
          hostName:
            type: string
          imagePullSecrets:
            type: array
            items:
              type: object
          initContainers:
            type: array
            items:
              type: object
          nodeName:
            type: string
          nodeSelector:
            type: object
            additionalProperties:
              type: string
          os:
            type: object
          overhead:
            type: object
            additionalProperties:
              type: object
          preemptionPolicy:
            type: string
          priority:
            type: int
          priorityClassName:
            type: string
          readinessGates:
            type: array
            items:
              type: object
          restartPolicy:
            type: string
          runtimeClassName:
            type: string
          schedulerName:
            type: string
          securityContext:
            type: object
          serviceAccount:
            type: string
          serviceAccountName:
            type: string
          setHostnameAsFQDN:
            type: boolean
          shareProcessNamespace:
            type: boolean
          subdomain:
            type: string
          terminationGracePeriodSeconds:
            type: long
          tolerations:
            type: array
            items:
              type: object
          topologySpreadConstraints:
            type: array
            items:
              type: object
          volumes:
            type: array
            items:
              type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: object
