get:
  summary: "List Deployments"
  description: >
    Historical list of all deployments for an Azure Elastigroup
  operationId: "elastigroupAzureDeploymentList"
  tags:
    - Elastigroup Azure Scale Set VMs
  parameters:
    - in: query
      name: accountId
      example: act-123abc
      description: >
        Your Spotinst accountid associated with your token
      schema:
        type: string
      required: false
    - $ref: "../../../commons/parameters/groupId.yaml"
    - in: query
      name: limit
      example: 5
      description: >
        Limits results
      schema:
        type: integer
      required: false
    - in: query
      name: sort
      example: created:ASC
      description: >
        Field to sort by the results
      schema:
        type: integer
      required: false
  responses:
    200:
      $ref: "../responses/deployment.yaml"
    400:
      description: "Bad Request"

put:
  summary: "Start Deployment"
  description: >
    Start a new Azure Elastigroup deployment
  operationId: "elastigroupAzureDeploymentStart"
  tags:
    - Elastigroup Azure Scale Set VMs
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../commons/parameters/groupId.yaml"
  responses:
    200:
      $ref: "../responses/deployment.yaml"
    400:
      description: "Bad Request"
