title: Target group configuration
type: object
description: |
  Object with target group configuration
allOf:
  - $ref: "../common/itfTargetGroupConfigProperties.yaml"
  - required:
      - vpcId
      - healthCheckPath
      - port
      - protocol