title: Load balancer configuration
type: object
description: |
  Contain all the loadBalancer properties.
required:
  - loadBalancerArn
  - listenerRules
properties:
  loadBalancerArn:
    type: string
    description:  |
      Identifier of the loadBalancer.
    example: "arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/app/my-load-balancer/50dc6c495c0c9188"
  listenerRules:
    type: array
    description: |
      The listener rules that should be maintained by ITF. List with a minimum of 1 elements.
    items:
      $ref: "../common/itfListenerRuleConfig.yaml"
  defaultStaticTargetGroups:
    type: array
    description: A Default Static Target group on the rule. List with a single element.
    items:
      $ref: "../common/itfStaticTargetGroupConfig.yaml"