title: Listener rule configuration
type: object
description: |
  Contain all the rule properties.
required:
  - ruleArn
properties:
  ruleArn:
    type: string
    description: |
      Identifier of the rule.
    example: "arn:aws:elasticloadbalancing:us-west-2:123456789012:listener-rule/app/0123456789012345/1234567890123456/234567890123456"
  staticTargetGroups:
    type: array
    description: A Static Target group on the rule. List with a single element.
    items:
      $ref: "../common/itfStaticTargetGroupConfig.yaml"
    example: [ {
      "arn": "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/blue-targets/73e2d6bc24d8a068",
      "percentage": 0.5
    } ]