title: Static target group configuration
type: object
description: |
  Static target group configuration
required:
  - arn
  - percentage
properties:
  arn:
    type: string
    description: |
      Identifier of the target group in AWS
    example: "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/blue-targets/73e2d6bc24d8a067"
  percentage:
    type: number
    description: |
      A float number in the range of 0.1-10
    example: 0.4