type: object
title: shielded-instance-config
description: >
  The Ocean Shielded Instance Config object.
properties:
  enableSecureBoot:
    type: boolean
    description: >
      Enable the secure boot parameter on the Gcp instances.
    example: true
  enableIntegrityMonitoring:
    type: boolean
    description: >
      Enable the integrity monitoring parameter on the Gcp instances.
    example: true