summary: Ocean CD
put:
  summary: "Update OceanCD Environment"
  description: >
    Update Ocean CD environment parameters.

    *All non included fields will be nullified*
  operationId: "OceanCDEnvironmentUpdate"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The name identifier of the OceanCD environment
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanCDEnvRequest.yaml"
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
patch:
  summary: "Patch OceanCD Environment"
  description: >
    Partial update Ocean CD environment parameters.
  operationId: "OceanCDEnvironmentPatch"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The name identifier of the OceanCD environment
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanCDEnvRequest.yaml"
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
get:
  summary: "Get OceanCD Environment"
  description: >
    Get the configuration of an existing Ocean CD environment.
  operationId: "oceanCDEnvironmentGet"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: Prod
      description: >
        The name identifier of the OceanCD environment
  responses:
    200:
      $ref: "../responses/oceanCDEnvResponse.yaml"
    400:
      description: "Bad Request"
delete:
  summary: "Delete OceanCD Environment"
  description: >
    Delete an existing Ocean CD environment.
  operationId: "OceanCDEnvironmentDelete"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: Prod
      description: >
        The name identifier of the OceanCD environment
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
